/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AppointmentsRouteImport } from './routes/appointments'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatmentsWartRemovalArmoorRouteImport } from './routes/treatments.wart-removal-armoor'
import { Route as TreatmentsVitiligoTreatmentArmoorRouteImport } from './routes/treatments.vitiligo-treatment-armoor'
import { Route as TreatmentsSkinAllergyTreatmentArmoorRouteImport } from './routes/treatments.skin-allergy-treatment-armoor'
import { Route as TreatmentsPsoriasisTreatmentArmoorRouteImport } from './routes/treatments.psoriasis-treatment-armoor'
import { Route as TreatmentsPigmentationTreatmentArmoorRouteImport } from './routes/treatments.pigmentation-treatment-armoor'
import { Route as TreatmentsNailDisordersArmoorRouteImport } from './routes/treatments.nail-disorders-armoor'
import { Route as TreatmentsMoleRemovalArmoorRouteImport } from './routes/treatments.mole-removal-armoor'
import { Route as TreatmentsHairLossTreatmentArmoorRouteImport } from './routes/treatments.hair-loss-treatment-armoor'
import { Route as TreatmentsFungalInfectionTreatmentArmoorRouteImport } from './routes/treatments.fungal-infection-treatment-armoor'
import { Route as TreatmentsEczemaTreatmentArmoorRouteImport } from './routes/treatments.eczema-treatment-armoor'
import { Route as TreatmentsDandruffTreatmentArmoorRouteImport } from './routes/treatments.dandruff-treatment-armoor'
import { Route as TreatmentsAcneTreatmentArmoorRouteImport } from './routes/treatments.acne-treatment-armoor'
import { Route as TreatmentsSlugRouteImport } from './routes/treatments.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AppointmentsRoute = AppointmentsRouteImport.update({
  id: '/appointments',
  path: '/appointments',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsWartRemovalArmoorRoute =
  TreatmentsWartRemovalArmoorRouteImport.update({
    id: '/wart-removal-armoor',
    path: '/wart-removal-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsVitiligoTreatmentArmoorRoute =
  TreatmentsVitiligoTreatmentArmoorRouteImport.update({
    id: '/vitiligo-treatment-armoor',
    path: '/vitiligo-treatment-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsSkinAllergyTreatmentArmoorRoute =
  TreatmentsSkinAllergyTreatmentArmoorRouteImport.update({
    id: '/skin-allergy-treatment-armoor',
    path: '/skin-allergy-treatment-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsPsoriasisTreatmentArmoorRoute =
  TreatmentsPsoriasisTreatmentArmoorRouteImport.update({
    id: '/psoriasis-treatment-armoor',
    path: '/psoriasis-treatment-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsPigmentationTreatmentArmoorRoute =
  TreatmentsPigmentationTreatmentArmoorRouteImport.update({
    id: '/pigmentation-treatment-armoor',
    path: '/pigmentation-treatment-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsNailDisordersArmoorRoute =
  TreatmentsNailDisordersArmoorRouteImport.update({
    id: '/nail-disorders-armoor',
    path: '/nail-disorders-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsMoleRemovalArmoorRoute =
  TreatmentsMoleRemovalArmoorRouteImport.update({
    id: '/mole-removal-armoor',
    path: '/mole-removal-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsHairLossTreatmentArmoorRoute =
  TreatmentsHairLossTreatmentArmoorRouteImport.update({
    id: '/hair-loss-treatment-armoor',
    path: '/hair-loss-treatment-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsFungalInfectionTreatmentArmoorRoute =
  TreatmentsFungalInfectionTreatmentArmoorRouteImport.update({
    id: '/fungal-infection-treatment-armoor',
    path: '/fungal-infection-treatment-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsEczemaTreatmentArmoorRoute =
  TreatmentsEczemaTreatmentArmoorRouteImport.update({
    id: '/eczema-treatment-armoor',
    path: '/eczema-treatment-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsDandruffTreatmentArmoorRoute =
  TreatmentsDandruffTreatmentArmoorRouteImport.update({
    id: '/dandruff-treatment-armoor',
    path: '/dandruff-treatment-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsAcneTreatmentArmoorRoute =
  TreatmentsAcneTreatmentArmoorRouteImport.update({
    id: '/acne-treatment-armoor',
    path: '/acne-treatment-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsSlugRoute = TreatmentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TreatmentsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/blog': typeof BlogRouteWithChildren
  '/treatments': typeof TreatmentsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/treatments/acne-treatment-armoor': typeof TreatmentsAcneTreatmentArmoorRoute
  '/treatments/dandruff-treatment-armoor': typeof TreatmentsDandruffTreatmentArmoorRoute
  '/treatments/eczema-treatment-armoor': typeof TreatmentsEczemaTreatmentArmoorRoute
  '/treatments/fungal-infection-treatment-armoor': typeof TreatmentsFungalInfectionTreatmentArmoorRoute
  '/treatments/hair-loss-treatment-armoor': typeof TreatmentsHairLossTreatmentArmoorRoute
  '/treatments/mole-removal-armoor': typeof TreatmentsMoleRemovalArmoorRoute
  '/treatments/nail-disorders-armoor': typeof TreatmentsNailDisordersArmoorRoute
  '/treatments/pigmentation-treatment-armoor': typeof TreatmentsPigmentationTreatmentArmoorRoute
  '/treatments/psoriasis-treatment-armoor': typeof TreatmentsPsoriasisTreatmentArmoorRoute
  '/treatments/skin-allergy-treatment-armoor': typeof TreatmentsSkinAllergyTreatmentArmoorRoute
  '/treatments/vitiligo-treatment-armoor': typeof TreatmentsVitiligoTreatmentArmoorRoute
  '/treatments/wart-removal-armoor': typeof TreatmentsWartRemovalArmoorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/blog': typeof BlogRouteWithChildren
  '/treatments': typeof TreatmentsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/treatments/acne-treatment-armoor': typeof TreatmentsAcneTreatmentArmoorRoute
  '/treatments/dandruff-treatment-armoor': typeof TreatmentsDandruffTreatmentArmoorRoute
  '/treatments/eczema-treatment-armoor': typeof TreatmentsEczemaTreatmentArmoorRoute
  '/treatments/fungal-infection-treatment-armoor': typeof TreatmentsFungalInfectionTreatmentArmoorRoute
  '/treatments/hair-loss-treatment-armoor': typeof TreatmentsHairLossTreatmentArmoorRoute
  '/treatments/mole-removal-armoor': typeof TreatmentsMoleRemovalArmoorRoute
  '/treatments/nail-disorders-armoor': typeof TreatmentsNailDisordersArmoorRoute
  '/treatments/pigmentation-treatment-armoor': typeof TreatmentsPigmentationTreatmentArmoorRoute
  '/treatments/psoriasis-treatment-armoor': typeof TreatmentsPsoriasisTreatmentArmoorRoute
  '/treatments/skin-allergy-treatment-armoor': typeof TreatmentsSkinAllergyTreatmentArmoorRoute
  '/treatments/vitiligo-treatment-armoor': typeof TreatmentsVitiligoTreatmentArmoorRoute
  '/treatments/wart-removal-armoor': typeof TreatmentsWartRemovalArmoorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/appointments': typeof AppointmentsRoute
  '/blog': typeof BlogRouteWithChildren
  '/treatments': typeof TreatmentsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/treatments/acne-treatment-armoor': typeof TreatmentsAcneTreatmentArmoorRoute
  '/treatments/dandruff-treatment-armoor': typeof TreatmentsDandruffTreatmentArmoorRoute
  '/treatments/eczema-treatment-armoor': typeof TreatmentsEczemaTreatmentArmoorRoute
  '/treatments/fungal-infection-treatment-armoor': typeof TreatmentsFungalInfectionTreatmentArmoorRoute
  '/treatments/hair-loss-treatment-armoor': typeof TreatmentsHairLossTreatmentArmoorRoute
  '/treatments/mole-removal-armoor': typeof TreatmentsMoleRemovalArmoorRoute
  '/treatments/nail-disorders-armoor': typeof TreatmentsNailDisordersArmoorRoute
  '/treatments/pigmentation-treatment-armoor': typeof TreatmentsPigmentationTreatmentArmoorRoute
  '/treatments/psoriasis-treatment-armoor': typeof TreatmentsPsoriasisTreatmentArmoorRoute
  '/treatments/skin-allergy-treatment-armoor': typeof TreatmentsSkinAllergyTreatmentArmoorRoute
  '/treatments/vitiligo-treatment-armoor': typeof TreatmentsVitiligoTreatmentArmoorRoute
  '/treatments/wart-removal-armoor': typeof TreatmentsWartRemovalArmoorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/appointments'
    | '/blog'
    | '/treatments'
    | '/blog/$slug'
    | '/treatments/$slug'
    | '/treatments/acne-treatment-armoor'
    | '/treatments/dandruff-treatment-armoor'
    | '/treatments/eczema-treatment-armoor'
    | '/treatments/fungal-infection-treatment-armoor'
    | '/treatments/hair-loss-treatment-armoor'
    | '/treatments/mole-removal-armoor'
    | '/treatments/nail-disorders-armoor'
    | '/treatments/pigmentation-treatment-armoor'
    | '/treatments/psoriasis-treatment-armoor'
    | '/treatments/skin-allergy-treatment-armoor'
    | '/treatments/vitiligo-treatment-armoor'
    | '/treatments/wart-removal-armoor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/appointments'
    | '/blog'
    | '/treatments'
    | '/blog/$slug'
    | '/treatments/$slug'
    | '/treatments/acne-treatment-armoor'
    | '/treatments/dandruff-treatment-armoor'
    | '/treatments/eczema-treatment-armoor'
    | '/treatments/fungal-infection-treatment-armoor'
    | '/treatments/hair-loss-treatment-armoor'
    | '/treatments/mole-removal-armoor'
    | '/treatments/nail-disorders-armoor'
    | '/treatments/pigmentation-treatment-armoor'
    | '/treatments/psoriasis-treatment-armoor'
    | '/treatments/skin-allergy-treatment-armoor'
    | '/treatments/vitiligo-treatment-armoor'
    | '/treatments/wart-removal-armoor'
  id:
    | '__root__'
    | '/'
    | '/appointments'
    | '/blog'
    | '/treatments'
    | '/blog/$slug'
    | '/treatments/$slug'
    | '/treatments/acne-treatment-armoor'
    | '/treatments/dandruff-treatment-armoor'
    | '/treatments/eczema-treatment-armoor'
    | '/treatments/fungal-infection-treatment-armoor'
    | '/treatments/hair-loss-treatment-armoor'
    | '/treatments/mole-removal-armoor'
    | '/treatments/nail-disorders-armoor'
    | '/treatments/pigmentation-treatment-armoor'
    | '/treatments/psoriasis-treatment-armoor'
    | '/treatments/skin-allergy-treatment-armoor'
    | '/treatments/vitiligo-treatment-armoor'
    | '/treatments/wart-removal-armoor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppointmentsRoute: typeof AppointmentsRoute
  BlogRoute: typeof BlogRouteWithChildren
  TreatmentsRoute: typeof TreatmentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/appointments': {
      id: '/appointments'
      path: '/appointments'
      fullPath: '/appointments'
      preLoaderRoute: typeof AppointmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/wart-removal-armoor': {
      id: '/treatments/wart-removal-armoor'
      path: '/wart-removal-armoor'
      fullPath: '/treatments/wart-removal-armoor'
      preLoaderRoute: typeof TreatmentsWartRemovalArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/vitiligo-treatment-armoor': {
      id: '/treatments/vitiligo-treatment-armoor'
      path: '/vitiligo-treatment-armoor'
      fullPath: '/treatments/vitiligo-treatment-armoor'
      preLoaderRoute: typeof TreatmentsVitiligoTreatmentArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/skin-allergy-treatment-armoor': {
      id: '/treatments/skin-allergy-treatment-armoor'
      path: '/skin-allergy-treatment-armoor'
      fullPath: '/treatments/skin-allergy-treatment-armoor'
      preLoaderRoute: typeof TreatmentsSkinAllergyTreatmentArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/psoriasis-treatment-armoor': {
      id: '/treatments/psoriasis-treatment-armoor'
      path: '/psoriasis-treatment-armoor'
      fullPath: '/treatments/psoriasis-treatment-armoor'
      preLoaderRoute: typeof TreatmentsPsoriasisTreatmentArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/pigmentation-treatment-armoor': {
      id: '/treatments/pigmentation-treatment-armoor'
      path: '/pigmentation-treatment-armoor'
      fullPath: '/treatments/pigmentation-treatment-armoor'
      preLoaderRoute: typeof TreatmentsPigmentationTreatmentArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/nail-disorders-armoor': {
      id: '/treatments/nail-disorders-armoor'
      path: '/nail-disorders-armoor'
      fullPath: '/treatments/nail-disorders-armoor'
      preLoaderRoute: typeof TreatmentsNailDisordersArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/mole-removal-armoor': {
      id: '/treatments/mole-removal-armoor'
      path: '/mole-removal-armoor'
      fullPath: '/treatments/mole-removal-armoor'
      preLoaderRoute: typeof TreatmentsMoleRemovalArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/hair-loss-treatment-armoor': {
      id: '/treatments/hair-loss-treatment-armoor'
      path: '/hair-loss-treatment-armoor'
      fullPath: '/treatments/hair-loss-treatment-armoor'
      preLoaderRoute: typeof TreatmentsHairLossTreatmentArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/fungal-infection-treatment-armoor': {
      id: '/treatments/fungal-infection-treatment-armoor'
      path: '/fungal-infection-treatment-armoor'
      fullPath: '/treatments/fungal-infection-treatment-armoor'
      preLoaderRoute: typeof TreatmentsFungalInfectionTreatmentArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/eczema-treatment-armoor': {
      id: '/treatments/eczema-treatment-armoor'
      path: '/eczema-treatment-armoor'
      fullPath: '/treatments/eczema-treatment-armoor'
      preLoaderRoute: typeof TreatmentsEczemaTreatmentArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/dandruff-treatment-armoor': {
      id: '/treatments/dandruff-treatment-armoor'
      path: '/dandruff-treatment-armoor'
      fullPath: '/treatments/dandruff-treatment-armoor'
      preLoaderRoute: typeof TreatmentsDandruffTreatmentArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/acne-treatment-armoor': {
      id: '/treatments/acne-treatment-armoor'
      path: '/acne-treatment-armoor'
      fullPath: '/treatments/acne-treatment-armoor'
      preLoaderRoute: typeof TreatmentsAcneTreatmentArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/$slug': {
      id: '/treatments/$slug'
      path: '/$slug'
      fullPath: '/treatments/$slug'
      preLoaderRoute: typeof TreatmentsSlugRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface TreatmentsRouteChildren {
  TreatmentsSlugRoute: typeof TreatmentsSlugRoute
  TreatmentsAcneTreatmentArmoorRoute: typeof TreatmentsAcneTreatmentArmoorRoute
  TreatmentsDandruffTreatmentArmoorRoute: typeof TreatmentsDandruffTreatmentArmoorRoute
  TreatmentsEczemaTreatmentArmoorRoute: typeof TreatmentsEczemaTreatmentArmoorRoute
  TreatmentsFungalInfectionTreatmentArmoorRoute: typeof TreatmentsFungalInfectionTreatmentArmoorRoute
  TreatmentsHairLossTreatmentArmoorRoute: typeof TreatmentsHairLossTreatmentArmoorRoute
  TreatmentsMoleRemovalArmoorRoute: typeof TreatmentsMoleRemovalArmoorRoute
  TreatmentsNailDisordersArmoorRoute: typeof TreatmentsNailDisordersArmoorRoute
  TreatmentsPigmentationTreatmentArmoorRoute: typeof TreatmentsPigmentationTreatmentArmoorRoute
  TreatmentsPsoriasisTreatmentArmoorRoute: typeof TreatmentsPsoriasisTreatmentArmoorRoute
  TreatmentsSkinAllergyTreatmentArmoorRoute: typeof TreatmentsSkinAllergyTreatmentArmoorRoute
  TreatmentsVitiligoTreatmentArmoorRoute: typeof TreatmentsVitiligoTreatmentArmoorRoute
  TreatmentsWartRemovalArmoorRoute: typeof TreatmentsWartRemovalArmoorRoute
}

const TreatmentsRouteChildren: TreatmentsRouteChildren = {
  TreatmentsSlugRoute: TreatmentsSlugRoute,
  TreatmentsAcneTreatmentArmoorRoute: TreatmentsAcneTreatmentArmoorRoute,
  TreatmentsDandruffTreatmentArmoorRoute:
    TreatmentsDandruffTreatmentArmoorRoute,
  TreatmentsEczemaTreatmentArmoorRoute: TreatmentsEczemaTreatmentArmoorRoute,
  TreatmentsFungalInfectionTreatmentArmoorRoute:
    TreatmentsFungalInfectionTreatmentArmoorRoute,
  TreatmentsHairLossTreatmentArmoorRoute:
    TreatmentsHairLossTreatmentArmoorRoute,
  TreatmentsMoleRemovalArmoorRoute: TreatmentsMoleRemovalArmoorRoute,
  TreatmentsNailDisordersArmoorRoute: TreatmentsNailDisordersArmoorRoute,
  TreatmentsPigmentationTreatmentArmoorRoute:
    TreatmentsPigmentationTreatmentArmoorRoute,
  TreatmentsPsoriasisTreatmentArmoorRoute:
    TreatmentsPsoriasisTreatmentArmoorRoute,
  TreatmentsSkinAllergyTreatmentArmoorRoute:
    TreatmentsSkinAllergyTreatmentArmoorRoute,
  TreatmentsVitiligoTreatmentArmoorRoute:
    TreatmentsVitiligoTreatmentArmoorRoute,
  TreatmentsWartRemovalArmoorRoute: TreatmentsWartRemovalArmoorRoute,
}

const TreatmentsRouteWithChildren = TreatmentsRoute._addFileChildren(
  TreatmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppointmentsRoute: AppointmentsRoute,
  BlogRoute: BlogRouteWithChildren,
  TreatmentsRoute: TreatmentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
