/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as TreatmentsRouteImport } from './routes/treatments'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as IndexRouteImport } from './routes/index'
import { Route as TreatmentsPsoriasisTreatmentArmoorRouteImport } from './routes/treatments.psoriasis-treatment-armoor'
import { Route as TreatmentsHairFallTreatmentArmoorRouteImport } from './routes/treatments.hair-fall-treatment-armoor'
import { Route as TreatmentsEczemaTreatmentArmoorRouteImport } from './routes/treatments.eczema-treatment-armoor'
import { Route as TreatmentsAcneTreatmentArmoorRouteImport } from './routes/treatments.acne-treatment-armoor'
import { Route as TreatmentsSlugRouteImport } from './routes/treatments.$slug'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'

const TreatmentsRoute = TreatmentsRouteImport.update({
  id: '/treatments',
  path: '/treatments',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const TreatmentsPsoriasisTreatmentArmoorRoute =
  TreatmentsPsoriasisTreatmentArmoorRouteImport.update({
    id: '/psoriasis-treatment-armoor',
    path: '/psoriasis-treatment-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsHairFallTreatmentArmoorRoute =
  TreatmentsHairFallTreatmentArmoorRouteImport.update({
    id: '/hair-fall-treatment-armoor',
    path: '/hair-fall-treatment-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsEczemaTreatmentArmoorRoute =
  TreatmentsEczemaTreatmentArmoorRouteImport.update({
    id: '/eczema-treatment-armoor',
    path: '/eczema-treatment-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsAcneTreatmentArmoorRoute =
  TreatmentsAcneTreatmentArmoorRouteImport.update({
    id: '/acne-treatment-armoor',
    path: '/acne-treatment-armoor',
    getParentRoute: () => TreatmentsRoute,
  } as any)
const TreatmentsSlugRoute = TreatmentsSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => TreatmentsRoute,
} as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/treatments': typeof TreatmentsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/treatments/acne-treatment-armoor': typeof TreatmentsAcneTreatmentArmoorRoute
  '/treatments/eczema-treatment-armoor': typeof TreatmentsEczemaTreatmentArmoorRoute
  '/treatments/hair-fall-treatment-armoor': typeof TreatmentsHairFallTreatmentArmoorRoute
  '/treatments/psoriasis-treatment-armoor': typeof TreatmentsPsoriasisTreatmentArmoorRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/treatments': typeof TreatmentsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/treatments/acne-treatment-armoor': typeof TreatmentsAcneTreatmentArmoorRoute
  '/treatments/eczema-treatment-armoor': typeof TreatmentsEczemaTreatmentArmoorRoute
  '/treatments/hair-fall-treatment-armoor': typeof TreatmentsHairFallTreatmentArmoorRoute
  '/treatments/psoriasis-treatment-armoor': typeof TreatmentsPsoriasisTreatmentArmoorRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/blog': typeof BlogRouteWithChildren
  '/treatments': typeof TreatmentsRouteWithChildren
  '/blog/$slug': typeof BlogSlugRoute
  '/treatments/$slug': typeof TreatmentsSlugRoute
  '/treatments/acne-treatment-armoor': typeof TreatmentsAcneTreatmentArmoorRoute
  '/treatments/eczema-treatment-armoor': typeof TreatmentsEczemaTreatmentArmoorRoute
  '/treatments/hair-fall-treatment-armoor': typeof TreatmentsHairFallTreatmentArmoorRoute
  '/treatments/psoriasis-treatment-armoor': typeof TreatmentsPsoriasisTreatmentArmoorRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/blog'
    | '/treatments'
    | '/blog/$slug'
    | '/treatments/$slug'
    | '/treatments/acne-treatment-armoor'
    | '/treatments/eczema-treatment-armoor'
    | '/treatments/hair-fall-treatment-armoor'
    | '/treatments/psoriasis-treatment-armoor'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/blog'
    | '/treatments'
    | '/blog/$slug'
    | '/treatments/$slug'
    | '/treatments/acne-treatment-armoor'
    | '/treatments/eczema-treatment-armoor'
    | '/treatments/hair-fall-treatment-armoor'
    | '/treatments/psoriasis-treatment-armoor'
  id:
    | '__root__'
    | '/'
    | '/blog'
    | '/treatments'
    | '/blog/$slug'
    | '/treatments/$slug'
    | '/treatments/acne-treatment-armoor'
    | '/treatments/eczema-treatment-armoor'
    | '/treatments/hair-fall-treatment-armoor'
    | '/treatments/psoriasis-treatment-armoor'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BlogRoute: typeof BlogRouteWithChildren
  TreatmentsRoute: typeof TreatmentsRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/treatments': {
      id: '/treatments'
      path: '/treatments'
      fullPath: '/treatments'
      preLoaderRoute: typeof TreatmentsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treatments/psoriasis-treatment-armoor': {
      id: '/treatments/psoriasis-treatment-armoor'
      path: '/psoriasis-treatment-armoor'
      fullPath: '/treatments/psoriasis-treatment-armoor'
      preLoaderRoute: typeof TreatmentsPsoriasisTreatmentArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/hair-fall-treatment-armoor': {
      id: '/treatments/hair-fall-treatment-armoor'
      path: '/hair-fall-treatment-armoor'
      fullPath: '/treatments/hair-fall-treatment-armoor'
      preLoaderRoute: typeof TreatmentsHairFallTreatmentArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/eczema-treatment-armoor': {
      id: '/treatments/eczema-treatment-armoor'
      path: '/eczema-treatment-armoor'
      fullPath: '/treatments/eczema-treatment-armoor'
      preLoaderRoute: typeof TreatmentsEczemaTreatmentArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/acne-treatment-armoor': {
      id: '/treatments/acne-treatment-armoor'
      path: '/acne-treatment-armoor'
      fullPath: '/treatments/acne-treatment-armoor'
      preLoaderRoute: typeof TreatmentsAcneTreatmentArmoorRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/treatments/$slug': {
      id: '/treatments/$slug'
      path: '/$slug'
      fullPath: '/treatments/$slug'
      preLoaderRoute: typeof TreatmentsSlugRouteImport
      parentRoute: typeof TreatmentsRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface TreatmentsRouteChildren {
  TreatmentsSlugRoute: typeof TreatmentsSlugRoute
  TreatmentsAcneTreatmentArmoorRoute: typeof TreatmentsAcneTreatmentArmoorRoute
  TreatmentsEczemaTreatmentArmoorRoute: typeof TreatmentsEczemaTreatmentArmoorRoute
  TreatmentsHairFallTreatmentArmoorRoute: typeof TreatmentsHairFallTreatmentArmoorRoute
  TreatmentsPsoriasisTreatmentArmoorRoute: typeof TreatmentsPsoriasisTreatmentArmoorRoute
}

const TreatmentsRouteChildren: TreatmentsRouteChildren = {
  TreatmentsSlugRoute: TreatmentsSlugRoute,
  TreatmentsAcneTreatmentArmoorRoute: TreatmentsAcneTreatmentArmoorRoute,
  TreatmentsEczemaTreatmentArmoorRoute: TreatmentsEczemaTreatmentArmoorRoute,
  TreatmentsHairFallTreatmentArmoorRoute:
    TreatmentsHairFallTreatmentArmoorRoute,
  TreatmentsPsoriasisTreatmentArmoorRoute:
    TreatmentsPsoriasisTreatmentArmoorRoute,
}

const TreatmentsRouteWithChildren = TreatmentsRoute._addFileChildren(
  TreatmentsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BlogRoute: BlogRouteWithChildren,
  TreatmentsRoute: TreatmentsRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
